---
name: Build
on: workflow_dispatch

env:
  REGISTRY_IMAGE: kirillzak/docker-almalinux-ansible

jobs:
  test-build-8:
    name: Test build of image
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/ppc64le
          - linux/s390x
        version_branch: [8]
        version_minor_release: [5, 6, 7, 8, 9, 10]
        exclude:
          - version_branch: 8
            version_minor_release: 5
            platform: linux/s390x

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build an image
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./almalinux${{ matrix.version_branch }}/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true
          push: false
          tags: |
            kirillzak/docker-almalinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  test-build-9:
    name: Test build of image
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/ppc64le
          - linux/s390x
        version_branch: [9]
        version_minor_release: [0, 1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build an image
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./almalinux${{ matrix.version_branch }}/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true
          push: false
          tags: |
            kirillzak/docker-almalinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  test-build-10:
    name: Test build of image
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/ppc64le
          - linux/s390x
        version_branch: [10]
        version_minor_release: [0]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build an image
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./almalinux${{ matrix.version_branch }}/Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true
          push: false
          tags: |
            kirillzak/docker-almalinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
